# general.import = [ "~/Dotfiles/themes/catppuccin/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal.family = "Jetbrains mono "
bold.family = "Jetbrains mono "
italic.family = "Jetbrains mono "
bold_italic.family = "Jetbrains mono "
size = 12
offset.x = 0
offset.y = 1

[window]
dynamic_padding = true
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
