general.import = [ "~/Dotfiles/themes/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal.family = "Jetbrains mono "
bold.family = "Jetbrains mono "
italic.family = "Jetbrains mono "
bold_italic.family = "Jetbrains mono "
size = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
