[font]
size = 13.0
offset = { x = -1, y = 1 } # x: line spacing, y: letter spacing

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "bold_italic"

[window]
padding.x = 0
padding.y = 0
opacity = 1.00
blur = true
dynamic_padding = true
decorations = "None"

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[cursor]
style = { shape = "Underline", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

# [colors.primary]
# background = "#000000"
# background = "#212122"
# foreground = "#ffffff"

[scrolling]
history = 10000
multiplier = 10
