local yellow_shade = {
  amber = "#FFBF00",
  apricot = "#FBCEB1",
  arylide_yellow = "#E9D66B",
  aureolin = "#FDEE00",
  beige = "#F5F5DC",
  buff = "#E0AB76",
  canary = "#FFEF00",
  champagne = "#F7E7CE",
  chartreuse = "#DFFF00",
  chrome_yellow = "#FFA700",

  citron = "#DDD06A",
  citrine = "#E4D00A",
  corn = "#FBEC5D",
  cosmic_latte = "#FFF8E7",
  cream = "#FFFDD0",
  dark_goldenrod = "#B8860B",
  ecru = "#CDB280",
  flax = "#EEDC82",
  gamboge = "#EF9B0F",
  gold = "#FFD700",
  gold_metallic = "#D4AF37",

  goldenrod = "#DAA520",
  green_earth = "#DADD98",
  harvest_gold = "#DA9100",
  icterine = "#FCF75E",
  isabelline = "#F4F0EC",
  ivory = "#FFFFF0",
  jasmine = "#F8DE7E",
  jonquil = "#FACA16",
  khaki = "#C3B091",
  lemon_chiffon = "#FFFACD",
  lemon_lime = "#E3FF00",

  light_yellow = "#FFFFE0",
  lion = "#C19A6B",
  maize = "#FFCB05",
  marigold = "#EAA221",
  mikado_yellow = "#FFC40C",
  mindaro = "#E3F988",
  mustard = "#FFDB58",
  naples_yellow = "#FADA5E",
  navajo_white = "#FFDEAD",
  old_gold = "#CFB53B",
  papaya_whip = "#FFEFD5",

  peach_yellow = "#FADFAD",
  pear = "#D1E231",
  saffron = "#F4C430",
  school_bus_yellow = "#FFD800",
  selective_yellow = "#FFBA00",
  stil_de_grain_yellow = "#FADA5E",
  straw = "#E4D96F",
  sunglow = "#FFCC33",
  sunset = "#FAD6A5",
  vanilla = "#F3E5AB",
  wheat = "#F5DEB3",
  xanthic = "#EEED09",
  yellow = "#FFFF00",
}


return yellow_shade
