local function get_palette(mode)
	if mode == "dark" then
		return require("colors.hqos.dark_palette")
	else
		return require("colors.hqos.palette")
	end
end

local c = get_palette(vim.g.hqos_mode or "light")

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()
	-- Editor
	hl(0, "Normal", { fg = c.fg, bg = c.bg })
	hl(0, "SignColumn", { fg = "NONE", bg = c.bg })
	hl(0, "MsgArea", { fg = c.fg, bg = c.bg })
	hl(0, "ModeMsg", { fg = c.fg, bg = c.alt_bg })
	hl(0, "MsgSeparator", { fg = c.fg, bg = c.bg })
	hl(0, "SpellBad", { fg = "NONE", bg = "NONE", sp = c._red, undercurl = true })
	hl(0, "SpellCap", { fg = "NONE", bg = "NONE", sp = c._orange, undercurl = true })
	hl(0, "SpellLocal", { fg = "NONE", bg = "NONE", sp = c._green, underline = true })
	hl(0, "SpellRare", { fg = "NONE", bg = "NONE", sp = c._purple, underline = true })
	hl(0, "NormalNC", { fg = c.fg, bg = c.bg })
	hl(0, "Pmenu", { fg = c.fg, bg = c.alt_bg })
	hl(0, "PmenuSel", { fg = c.bg, bg = c.alt_fg })
	hl(0, "WildMenu", { fg = c.bg, bg = c.alt_fg })
	hl(0, "CursorLineNr", { fg = c.alt_fg, bg = "NONE", bold = true })
	hl(0, "Folded", { fg = c._grey_dark, bg = c.cursorline })
	hl(0, "FoldColumn", { fg = c._grey_dark, bg = c.bg })
	hl(0, "LineNr", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "FloatBorder", { fg = c._grey_dark, bg = c.alt_bg })
	hl(0, "Whitespace", { fg = c.cursorline, bg = "NONE" })
	hl(0, "VertSplit", { fg = c._grey_dark, bg = c.bg })
	hl(0, "CursorLine", { fg = "NONE", bg = c.cursorline })
	hl(0, "CursorColumn", { fg = "NONE", bg = c.cursorline })
	hl(0, "ColorColumn", { fg = "NONE", bg = c.cursorline })
	hl(0, "NormalFloat", { fg = c.fg, bg = c.alt_bg })
	hl(0, "Visual", { fg = "NONE", bg = c._pink_light })
	hl(0, "VisualNOS", { fg = "NONE", bg = c.cursorline })
	hl(0, "WarningMsg", { fg = c._red, bg = c.bg })
	hl(0, "DiffText", { fg = c.bg, bg = c._purple })
	hl(0, "DiffAdd", { fg = c._green, bg = c.system_green_light })
	hl(0, "DiffChange", { fg = c._orange, bg = c.system_orange_light, underline = true })
	hl(0, "DiffDelete", { fg = c._red, bg = c.system_pink_light })
	hl(0, "QuickFixLine", { fg = "NONE", bg = c.cursorline })
	hl(0, "PmenuSbar", { fg = "NONE", bg = c.cursorline })
	hl(0, "PmenuThumb", { fg = "NONE", bg = c._grey_dark })
	hl(0, "MatchWord", { fg = "NONE", bg = "NONE", underline = true })
	hl(0, "MatchParen", { fg = c._red, bg = "NONE", underline = true, bold = true })
	hl(0, "MatchWordCur", { fg = "NONE", bg = "NONE", underline = true })
	hl(0, "MatchParenCur", { fg = "NONE", bg = "NONE", underline = true })
	hl(0, "Cursor", { fg = c.bg, bg = c.cursor_bg })
	hl(0, "lCursor", { fg = c.bg, bg = c.cursor_bg })
	hl(0, "CursorIM", { fg = c.bg, bg = c.cursor_bg })
	hl(0, "TermCursor", { fg = c.bg, bg = c.cursor_bg })
	hl(0, "TermCursorNC", { fg = c.bg, bg = c.cursor_bg })
	hl(0, "Conceal", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "Directory", { fg = c._green, bg = "NONE" })
	hl(0, "SpecialKey", { fg = c.alt_fg, bg = "NONE", bold = true })
	hl(0, "ErrorMsg", { fg = c._red, bg = c.bg, bold = true })
	hl(0, "Search", { fg = c.fg, bg = c._yellow })
	hl(0, "IncSearch", { fg = c.bg, bg = c._orange })
	hl(0, "Substitute", { fg = c.bg, bg = c._orange })
	hl(0, "MoreMsg", { fg = c._orange, bg = "NONE" })
	hl(0, "Question", { fg = c._orange, bg = "NONE" })
	hl(0, "EndOfBuffer", { fg = c.bg, bg = "NONE" })
	hl(0, "NonText", { fg = c.cursorline, bg = "NONE" })
	hl(0, "TabLine", { fg = c._grey_dark, bg = c.line })
	hl(0, "TabLineSel", { fg = c.fg, bg = c.bg })
	hl(0, "TabLineFill", { fg = c.line, bg = c.line })

	-- Code
	hl(0, "Comment", { fg = c._grey_dark, bg = "NONE", italic = true })
	hl(0, "Variable", { fg = c.fg, bg = "NONE" })
	hl(0, "String", { fg = c._green, bg = "NONE" })
	hl(0, "Character", { fg = c._green, bg = "NONE" })
	hl(0, "Number", { fg = c._orange, bg = "NONE" })
	hl(0, "Float", { fg = c._orange, bg = "NONE" })
	hl(0, "Boolean", { fg = c._purple, bg = "NONE" })
	hl(0, "Constant", { fg = c._red, bg = "NONE" })
	hl(0, "Type", { fg = c._pink, bg = "NONE" })
	hl(0, "Function", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "Keyword", { fg = c._purple, bg = "NONE" })
	hl(0, "Conditional", { fg = c._purple, bg = "NONE" })
	hl(0, "Repeat", { fg = c._purple, bg = "NONE" })
	hl(0, "Operator", { fg = c.fg, bg = "NONE" })
	hl(0, "PreProc", { fg = c._pink, bg = "NONE" })
	hl(0, "Include", { fg = c._pink, bg = "NONE" })
	hl(0, "Exception", { fg = c._red, bg = "NONE" })
	hl(0, "StorageClass", { fg = c._pink, bg = "NONE" })
	hl(0, "Structure", { fg = c._pink, bg = "NONE" })
	hl(0, "Typedef", { fg = c._pink, bg = "NONE" })
	hl(0, "Define", { fg = c._pink, bg = "NONE" })
	hl(0, "Macro", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "Debug", { fg = c._red, bg = "NONE" })
	hl(0, "Title", { fg = c.alt_fg, bg = "NONE", bold = true })
	hl(0, "Label", { fg = c.fg, bg = "NONE" })
	hl(0, "SpecialChar", { fg = c._green, bg = "NONE" })
	hl(0, "Delimiter", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "SpecialComment", { fg = c._pink_alt, bg = "NONE", italic = true })
	hl(0, "Tag", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "Bold", { fg = "NONE", bg = "NONE", bold = true })
	hl(0, "Italic", { fg = "NONE", bg = "NONE", italic = true })
	hl(0, "Underlined", { fg = "NONE", bg = "NONE", underline = true })
	hl(0, "Ignore", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "Todo", { fg = c._red, bg = "NONE", bold = true })
	hl(0, "Error", { fg = c._red, bg = "NONE", bold = true })
	hl(0, "Statement", { fg = c._purple, bg = "NONE" })
	hl(0, "Identifier", { fg = c.fg, bg = "NONE" })
	hl(0, "PreCondit", { fg = c._pink, bg = "NONE" })
	hl(0, "Special", { fg = c._pink_alt, bg = "NONE" })

	-- Treesitter
	hl(0, "TSComment", { link = "Comment" })
	hl(0, "TSVariable", { link = "Variable" })
	hl(0, "TSString", { link = "String" })
	hl(0, "TSStringRegex", { fg = c._green_alt, bg = "NONE" })
	hl(0, "TSStringEscape", { fg = c._orange, bg = "NONE" })
	hl(0, "TSCharacter", { link = "String" })
	hl(0, "TSCharacterSpecial", { link = "SpecialChar" })
	hl(0, "TSNumber", { link = "Number" })
	hl(0, "TSFloat", { link = "Float" })
	hl(0, "TSBoolean", { link = "Boolean" })
	hl(0, "TSConstant", { link = "Constant" })
	hl(0, "TSConstBuiltin", { fg = c._red, bg = "NONE", bold = true })
	hl(0, "TSConstructor", { link = "Type" })
	hl(0, "TSType", { link = "Type" })
	hl(0, "TSInclude", { link = "Include" })
	hl(0, "TSException", { link = "Exception" })
	hl(0, "TSKeyword", { link = "Keyword" })
	hl(0, "TSKeywordReturn", { fg = c._red, bg = "NONE" })
	hl(0, "TSKeywordOperator", { link = "Keyword" })
	hl(0, "TSKeywordFunction", { fg = c._purple, bg = "NONE" })
	hl(0, "TSFunction", { link = "Function" })
	hl(0, "TSFuncBuiltin", { fg = c.alt_fg, bg = "NONE", bold = true })
	hl(0, "TSMethod", { link = "Function" })
	hl(0, "TSFuncMacro", { fg = c._pink_alt, bg = "NONE" })
	hl(0, "TSConditional", { link = "Conditional" })
	hl(0, "TSRepeat", { link = "Repeat" })
	hl(0, "TSOperator", { link = "Operator" })
	hl(0, "TSPreProc", { link = "PreProc" })
	hl(0, "TSStorageClass", { link = "StorageClass" })
	hl(0, "TSStructure", { link = "Structure" })
	hl(0, "TSTypeDefinition", { link = "Typedef" })
	hl(0, "TSDefine", { link = "Define" })
	hl(0, "TSNote", { fg = c._green, bg = "NONE", bold = true })
	hl(0, "TSTodo", { link = "Todo" })
	hl(0, "TSDebug", { link = "Debug" })
	hl(0, "TSDanger", { link = "Error" })
	hl(0, "TSTitle", { link = "Title" })
	hl(0, "TSLabel", { link = "Label" })
	hl(0, "TSPunctDelimiter", { link = "Delimiter" })
	hl(0, "TSTagDelimiter", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "TSPunctBracket", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "TSPunctSpecial", { fg = c._pink_alt, bg = "NONE" })
	hl(0, "TSTag", { link = "Tag" })
	hl(0, "TSStrong", { link = "Bold" })
	hl(0, "TSEmphasis", { link = "Italic" })
	hl(0, "TSUnderline", { link = "Underline" })
	hl(0, "TSStrike", { fg = "NONE", bg = "NONE", strikethrough = true })
	hl(0, "TSStringSpecial", { fg = c._green_alt, bg = "NONE" })
	hl(0, "TSEnvironmentName", { fg = c._pink, bg = "NONE" })
	hl(0, "TSVariableBuiltin", { fg = c._red, bg = "NONE" })
	hl(0, "TSConstMacro", { fg = c._orange, bg = "NONE" })
	hl(0, "TSTypeBuiltin", { fg = c._pink, bg = "NONE", bold = true })
	hl(0, "TSAnnotation", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "TSNamespace", { fg = c._pink, bg = "NONE" })
	hl(0, "TSSymbol", { fg = c.fg, bg = "NONE" })
	hl(0, "TSField", { fg = c.fg, bg = "NONE" })
	hl(0, "TSProperty", { fg = c._pink_dark_alt, bg = "NONE" })
	hl(0, "TSParameter", { fg = c._pink_dark_alt, bg = "NONE" })
	hl(0, "TSParameterReference", { fg = c._pink_dark_alt, bg = "NONE" })
	hl(0, "TSAttribute", { fg = c._pink_alt, bg = "NONE" })
	hl(0, "TSText", { fg = c.fg, bg = "NONE" })
	hl(0, "TSTagAttribute", { fg = c._orange, bg = "NONE", italic = true })
	hl(0, "TSError", { fg = c._red, bg = "NONE" })
	hl(0, "TSWarning", { fg = c._orange, bg = "NONE" })
	hl(0, "TSQueryLinterError", { fg = c._red, bg = "NONE" })
	hl(0, "TSURI", { fg = c.alt_fg, bg = "NONE", underline = true })
	hl(0, "TSMath", { fg = c._orange, bg = "NONE" })
	hl(0, "TSLiteral", { fg = c._orange, bg = "NONE" })

	-- Markdown
	hl(0, "markdownBlockquote", { fg = c._orange, bg = "NONE" })
	hl(0, "markdownCode", { fg = c._green, bg = c.system_green_light })
	hl(0, "markdownCodeBlock", { fg = c._green, bg = c.system_green_light })
	hl(0, "markdownCodeDelimiter", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "markdownH1", { link = "Title" })
	hl(0, "markdownH2", { link = "Title" })
	hl(0, "markdownH3", { link = "Title" })
	hl(0, "markdownH4", { link = "Title" })
	hl(0, "markdownH5", { link = "Title" })
	hl(0, "markdownH6", { link = "Title" })
	hl(0, "markdownHeadingDelimiter", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "markdownHeadingRule", { fg = c.fg, bg = "NONE", bold = true })
	hl(0, "markdownId", { link = "Identifier" })
	hl(0, "markdownIdDeclaration", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "markdownIdDelimiter", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "markdownLinkDelimiter", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "markdownBold", { fg = c.alt_fg, bg = "NONE", bold = true })
	hl(0, "markdownItalic", { link = "Italic" })
	hl(0, "markdownBoldItalic", { fg = c._orange, bg = "NONE", bold = true, italic = true })
	hl(0, "markdownListMarker", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "markdownOrderedListMarker", { fg = c._purple, bg = "NONE" })
	hl(0, "markdownRule", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "markdownUrl", { fg = c.alt_fg, bg = "NONE", underdotted = true })
	hl(0, "markdownLinkText", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "markdownFootnote", { fg = c._orange, bg = "NONE" })
	hl(0, "markdownFootnoteDefinition", { fg = c._orange, bg = "NONE" })
	hl(0, "markdownEscape", { fg = c._orange, bg = "NONE" })

	-- WhichKey
	hl(0, "WhichKey", { fg = c._purple, bg = "NONE" })
	hl(0, "WhichKeySeperator", { fg = c._green, bg = "NONE" })
	hl(0, "WhichKeyGroup", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "WhichKeyDesc", { fg = c.fg, bg = "NONE" })
	hl(0, "WhichKeyFloat", { fg = "NONE", bg = c.alt_bg })

	-- Git
	hl(0, "SignAdd", { fg = c._green, bg = "NONE" })
	hl(0, "SignChange", { fg = c._orange, bg = "NONE" })
	hl(0, "SignDelete", { fg = c._red, bg = "NONE" })
	hl(0, "GitSignsAdd", { fg = c._green, bg = "NONE" })
	hl(0, "GitSignsChange", { fg = c._orange, bg = "NONE" })
	hl(0, "GitSignsDelete", { fg = c._red, bg = "NONE" })

	-- LSP
	hl(0, "DiagnosticHint", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "DiagnosticInfo", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "DiagnosticWarn", { fg = c._orange, bg = "NONE" })
	hl(0, "DiagnosticError", { fg = c._red, bg = "NONE" })
	hl(0, "DiagnosticOther", { fg = c._purple, bg = "NONE" })
	hl(0, "DiagnosticSignHint", { link = "DiagnosticHint" })
	hl(0, "DiagnosticSignInfo", { link = "DiagnosticInfo" })
	hl(0, "DiagnosticSignWarn", { link = "DiagnosticWarn" })
	hl(0, "DiagnosticSignError", { link = "DiagnosticError" })
	hl(0, "DiagnosticSignOther", { link = "DiagnosticOther" })
	hl(0, "DiagnosticSignWarning", { link = "DiagnosticWarn" })
	hl(0, "DiagnosticFloatingHint", { link = "DiagnosticHint" })
	hl(0, "DiagnosticFloatingInfo", { link = "DiagnosticInfo" })
	hl(0, "DiagnosticFloatingWarn", { link = "DiagnosticWarn" })
	hl(0, "DiagnosticFloatingError", { link = "DiagnosticError" })
	hl(0, "DiagnosticUnderlineHint", { fg = "NONE", bg = "NONE", sp = c.alt_fg, undercurl = true })
	hl(0, "DiagnosticUnderlineInfo", { fg = "NONE", bg = "NONE", sp = c.alt_fg, undercurl = true })
	hl(0, "DiagnosticUnderlineWarn", { fg = "NONE", bg = "NONE", sp = c._orange, undercurl = true })
	hl(0, "DiagnosticUnderlineError", { fg = "NONE", bg = "NONE", sp = c._red, undercurl = true })
	hl(0, "DiagnosticSignInformation", { link = "DiagnosticInfo" })
	hl(0, "DiagnosticVirtualTextHint", { fg = c.alt_fg, bg = c.cursorline })
	hl(0, "DiagnosticVirtualTextInfo", { fg = c.alt_fg, bg = c.cursorline })
	hl(0, "DiagnosticVirtualTextWarn", { fg = c._orange, bg = c.system_orange_light })
	hl(0, "DiagnosticVirtualTextError", { fg = c._red, bg = c.system_pink_light })
	hl(0, "LspDiagnosticsError", { fg = c._red, bg = "NONE" })
	hl(0, "LspDiagnosticsWarning", { fg = c._orange, bg = "NONE" })
	hl(0, "LspDiagnosticsInfo", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "LspDiagnosticsInformation", { link = "LspDiagnosticsInfo" })
	hl(0, "LspDiagnosticsHint", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "LspDiagnosticsDefaultError", { link = "LspDiagnosticsError" })
	hl(0, "LspDiagnosticsDefaultWarning", { link = "LspDiagnosticsWarning" })
	hl(0, "LspDiagnosticsDefaultInformation", { link = "LspDiagnosticsInfo" })
	hl(0, "LspDiagnosticsDefaultInfo", { link = "LspDiagnosticsInfo" })
	hl(0, "LspDiagnosticsDefaultHint", { link = "LspDiagnosticsHint" })
	hl(0, "LspDiagnosticsVirtualTextError", { link = "DiagnosticVirtualTextError" })
	hl(0, "LspDiagnosticsVirtualTextWarning", { link = "DiagnosticVirtualTextWarn" })
	hl(0, "LspDiagnosticsVirtualTextInformation", { link = "DiagnosticVirtualTextInfo" })
	hl(0, "LspDiagnosticsVirtualTextInfo", { link = "DiagnosticVirtualTextInfo" })
	hl(0, "LspDiagnosticsVirtualTextHint", { link = "DiagnosticVirtualTextHint" })
	hl(0, "LspDiagnosticsFloatingError", { link = "LspDiagnosticsError" })
	hl(0, "LspDiagnosticsFloatingWarning", { link = "LspDiagnosticsWarning" })
	hl(0, "LspDiagnosticsFloatingInformation", { link = "LspDiagnosticsInfo" })
	hl(0, "LspDiagnosticsFloatingInfo", { link = "LspDiagnosticsInfo" })
	hl(0, "LspDiagnosticsFloatingHint", { link = "LspDiagnosticsHint" })
	hl(0, "LspDiagnosticsSignError", { link = "LspDiagnosticsError" })
	hl(0, "LspDiagnosticsSignWarning", { link = "LspDiagnosticsWarning" })
	hl(0, "LspDiagnosticsSignInformation", { link = "LspDiagnosticsInfo" })
	hl(0, "LspDiagnosticsSignInfo", { link = "LspDiagnosticsInfo" })
	hl(0, "LspDiagnosticsSignHint", { link = "LspDiagnosticsHint" })
	hl(0, "LspDiagnosticsUnderlineError", { link = "DiagnosticUnderlineError" })
	hl(0, "LspDiagnosticsUnderlineWarning", { link = "DiagnosticUnderlineWarn" })
	hl(0, "LspDiagnosticsUnderlineInformation", { link = "DiagnosticUnderlineInfo" })
	hl(0, "LspDiagnosticsUnderlineInfo", { link = "DiagnosticUnderlineInfo" })
	hl(0, "LspDiagnosticsUnderlineHint", { link = "DiagnosticUnderlineHint" })
	hl(0, "LspReferenceRead", { fg = "NONE", bg = c.cursorline })
	hl(0, "LspReferenceText", { fg = "NONE", bg = c.cursorline })
	hl(0, "LspReferenceWrite", { fg = "NONE", bg = c.cursorline })
	hl(0, "LspCodeLens", { fg = c._grey_dark, bg = "NONE", italic = true })
	hl(0, "LspCodeLensSeparator", { fg = c._grey_dark, bg = "NONE", italic = true })

	-- Telescope
	hl(0, "TelescopeSelection", { fg = "NONE", bg = c.cursorline })
	hl(0, "TelescopeSelectionCaret", { fg = c._red, bg = c.cursorline })
	hl(0, "TelescopeMatching", { fg = c.alt_fg, bg = "NONE", bold = true })
	hl(0, "TelescopeBorder", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "TelescopeNormal", { fg = c.fg, bg = c.alt_bg })
	hl(0, "TelescopePromptTitle", { fg = c._orange, bg = "NONE" })
	hl(0, "TelescopePromptPrefix", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "TelescopeResultsTitle", { fg = c._orange, bg = "NONE" })
	hl(0, "TelescopePreviewTitle", { fg = c._orange, bg = "NONE" })
	hl(0, "TelescopePromptCounter", { fg = c._red, bg = "NONE" })
	hl(0, "TelescopePreviewHyphen", { fg = c._red, bg = "NONE" })

	-- NvimTree
	hl(0, "NvimTreeFolderIcon", { link = "Directory" })
	hl(0, "NvimTreeIndentMarker", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "NvimTreeNormal", { fg = c.fg, bg = c.alt_bg })
	hl(0, "NvimTreeVertSplit", { fg = c.alt_bg, bg = c.alt_bg })
	hl(0, "NvimTreeFolderName", { link = "Directory" })
	hl(0, "NvimTreeOpenedFolderName", { fg = c._green, bg = "NONE", bold = true, italic = true })
	hl(0, "NvimTreeEmptyFolderName", { fg = c._grey_dark, bg = "NONE", italic = true })
	hl(0, "NvimTreeGitIgnored", { fg = c._grey_dark, bg = "NONE", italic = true })
	hl(0, "NvimTreeImageFile", { fg = c._purple, bg = "NONE" })
	hl(0, "NvimTreeSpecialFile", { fg = c._orange, bg = "NONE" })
	hl(0, "NvimTreeEndOfBuffer", { fg = c.alt_bg, bg = "NONE" })
	hl(0, "NvimTreeCursorLine", { fg = "NONE", bg = c.cursorline })
	hl(0, "NvimTreeGitStaged", { fg = c._green_alt, bg = "NONE" })
	hl(0, "NvimTreeGitNew", { fg = c._green, bg = "NONE" })
	hl(0, "NvimTreeGitRenamed", { fg = c._green_alt, bg = "NONE" })
	hl(0, "NvimTreeGitDeleted", { fg = c._red, bg = "NONE" })
	hl(0, "NvimTreeGitMerge", { fg = c._orange, bg = "NONE" })
	hl(0, "NvimTreeGitDirty", { fg = c._orange, bg = "NONE" })
	hl(0, "NvimTreeSymlink", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "NvimTreeRootFolder", { fg = c.fg, bg = "NONE", bold = true })
	hl(0, "NvimTreeExecFile", { fg = c._green_alt, bg = "NONE" })

	-- StatusLine
	hl(0, "StatusLine", { fg = c._grey_dark, bg = c.bg })
	hl(0, "StatusLineNC", { fg = "NONE", bg = "NONE" })
	hl(0, "StatusLineSeparator", { fg = c.line, bg = "NONE" })
	hl(0, "StatusLineTerm", { fg = c.line, bg = "NONE" })
	hl(0, "StatusLineTermNC", { fg = c.line, bg = "NONE" })

	-- IndentBlankline
	hl(0, "IndentBlanklineContextChar", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "IndentBlanklineContextStart", { fg = "NONE", bg = "NONE", underline = true })
	hl(0, "IndentBlanklineChar", { fg = c.cursorline, bg = "NONE" })

	-- Dashboard
	hl(0, "DashboardHeader", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "DashboardCenter", { fg = c._purple, bg = "NONE" })
	hl(0, "DashboardFooter", { fg = c._green, bg = "NONE" })

	-- Cmp
	hl(0, "CmpItemAbbrDeprecated", { fg = c._grey_dark, bg = "NONE", strikethrough = true })
	hl(0, "CmpItemAbbrMatch", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "CmpItemAbbrMatchFuzzy", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "CmpItemKindFunction", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "CmpItemKindMethod", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "CmpItemKindConstructor", { fg = c._pink, bg = "NONE" })
	hl(0, "CmpItemKindClass", { fg = c._pink, bg = "NONE" })
	hl(0, "CmpItemKindEnum", { fg = c._pink, bg = "NONE" })
	hl(0, "CmpItemKindEvent", { fg = c._orange, bg = "NONE" })
	hl(0, "CmpItemKindInterface", { fg = c._pink, bg = "NONE" })
	hl(0, "CmpItemKindStruct", { fg = c._pink, bg = "NONE" })
	hl(0, "CmpItemKindVariable", { fg = c._pink_dark_alt, bg = "NONE" })
	hl(0, "CmpItemKindField", { fg = c._pink_dark_alt, bg = "NONE" })
	hl(0, "CmpItemKindProperty", { fg = c._pink_dark_alt, bg = "NONE" })
	hl(0, "CmpItemKindEnumMember", { fg = c._orange, bg = "NONE" })
	hl(0, "CmpItemKindConstant", { fg = c._red, bg = "NONE" })
	hl(0, "CmpItemKindKeyword", { fg = c._purple, bg = "NONE" })
	hl(0, "CmpItemKindModule", { fg = c._pink, bg = "NONE" })
	hl(0, "CmpItemKindValue", { fg = c.fg, bg = "NONE" })
	hl(0, "CmpItemKindUnit", { fg = c.fg, bg = "NONE" })
	hl(0, "CmpItemKindText", { fg = c.fg, bg = "NONE" })
	hl(0, "CmpItemKindSnippet", { fg = c._orange, bg = "NONE" })
	hl(0, "CmpItemKindFile", { fg = c.fg, bg = "NONE" })
	hl(0, "CmpItemKindFolder", { fg = c.fg, bg = "NONE" })
	hl(0, "CmpItemKindColor", { fg = c.fg, bg = "NONE" })
	hl(0, "CmpItemKindReference", { fg = c.fg, bg = "NONE" })
	hl(0, "CmpItemKindOperator", { fg = c.fg, bg = "NONE" })
	hl(0, "CmpItemKindTypeParameter", { fg = c._pink_dark_alt, bg = "NONE" })

	-- Misc
	hl(0, "diffAdded", { fg = c._green, bg = "NONE" })
	hl(0, "diffRemoved", { fg = c._red, bg = "NONE" })
	hl(0, "diffFileId", { fg = c.alt_fg, bg = "NONE", bold = true, reverse = true })
	hl(0, "diffFile", { fg = c.alt_bg, bg = "NONE" })
	hl(0, "diffNewFile", { fg = c._green, bg = "NONE" })
	hl(0, "diffOldFile", { fg = c._red, bg = "NONE" })
	hl(0, "debugPc", { fg = "NONE", bg = c.cursorline })
	hl(0, "debugBreakpoint", { fg = c._red, bg = "NONE", reverse = true })
	hl(0, "CodiVirtualText", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "DapBreakpoint", { fg = c._red, bg = "NONE" })

	-- Language specific
	hl(0, "xmlTag", { fg = c._pink, bg = "NONE" })
	hl(0, "xmlTagName", { fg = c._pink, bg = "NONE" })
	hl(0, "xmlEndTag", { fg = c._pink, bg = "NONE" })
	hl(0, "yamlPlainScalar", { fg = c._orange, bg = "NONE" })
	hl(0, "yamlTSField", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "luaFunc", { fg = c._orange, bg = "NONE" })
	hl(0, "luaFunction", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "htmlH1", { fg = c.fg, bg = "NONE" })
	hl(0, "htmlH2", { fg = c.fg, bg = "NONE" })
	hl(0, "htmlH3", { fg = c.fg, bg = "NONE" })
	hl(0, "htmlH4", { fg = c.fg, bg = "NONE" })
	hl(0, "htmlH5", { fg = c.fg, bg = "NONE" })
	hl(0, "htmlH6", { fg = c.fg, bg = "NONE" })
	hl(0, "htmlHead", { fg = c.fg, bg = "NONE" })
	hl(0, "htmlTitle", { fg = c.fg, bg = "NONE" })
	hl(0, "htmlArg", { fg = c._pink_alt, bg = "NONE" })
	hl(0, "htmlTag", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "htmlTagN", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "htmlTagName", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "htmlComment", { fg = c._grey_dark, bg = "NONE" })
	hl(0, "htmlLink", { fg = c.alt_fg, bg = "NONE", underline = true })
	hl(0, "cssBraces", { fg = c.fg, bg = "NONE" })
	hl(0, "cssInclude", { fg = c._purple, bg = "NONE" })
	hl(0, "cssTagName", { fg = c._orange, bg = "NONE" })
	hl(0, "cssClassName", { fg = c._orange, bg = "NONE" })
	hl(0, "cssPseudoClass", { fg = c._orange, bg = "NONE" })
	hl(0, "cssPseudoClassId", { fg = c._orange, bg = "NONE" })
	hl(0, "cssPseudoClassLang", { fg = c._orange, bg = "NONE" })
	hl(0, "cssIdentifier", { fg = c._orange, bg = "NONE" })
	hl(0, "cssProp", { fg = c.fg, bg = "NONE" })
	hl(0, "cssDefinition", { fg = c.fg, bg = "NONE" })
	hl(0, "cssAttr", { fg = c._orange, bg = "NONE" })
	hl(0, "cssAttrRegion", { fg = c._orange, bg = "NONE" })
	hl(0, "cssColor", { fg = c._orange, bg = "NONE" })
	hl(0, "cssFunction", { fg = c._purple, bg = "NONE" })
	hl(0, "cssFunctionName", { fg = c._orange, bg = "NONE" })
	hl(0, "cssVendor", { fg = c._orange, bg = "NONE" })
	hl(0, "cssValueNumber", { fg = c._orange, bg = "NONE" })
	hl(0, "cssValueLength", { fg = c._orange, bg = "NONE" })
	hl(0, "cssUnitDecorators", { fg = c._orange, bg = "NONE" })
	hl(0, "cssStyle", { fg = c.fg, bg = "NONE" })
	hl(0, "cssImportant", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "jsonKeyword", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "yamlBlockMappingKey", { fg = c.alt_fg, bg = "NONE" })
	hl(0, "tomlTSProperty", { fg = c.alt_fg, bg = "NONE" })
end

function theme.setup(opts)
	opts = opts or {}
	local mode = opts.mode or vim.g.hqos_mode or "light"

	vim.g.hqos_mode = mode

	-- Reload the palette with the new mode
	c = get_palette(mode)

	vim.cmd("highlight clear")
	if vim.fn.exists("syntax_on") then
		vim.cmd("syntax reset")
	end

	vim.g.colors_name = "hqos"
	theme.set_highlights()
end

function theme.toggle_mode()
	local current_mode = vim.g.hqos_mode or "light"
	local new_mode = current_mode == "light" and "dark" or "light"
	theme.setup({ mode = new_mode })
end

return theme
