local c = require("colors.hqos.dark_palette")

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()
  -- Editor
  hl(0, "Normal", { fg = c.fg, bg = c.bg })
  hl(0, "SignColumn", { fg = "NONE", bg = c.bg })
  hl(0, "MsgArea", { fg = c.fg, bg = c.bg })
  hl(0, "ModeMsg", { fg = c.fg, bg = c.alt_bg })
  hl(0, "MsgSeparator", { fg = c.fg, bg = c.bg })
  hl(0, "SpellBad", { fg = "NONE", bg = "NONE", sp = c._red, undercurl = true })
  hl(0, "SpellCap", { fg = "NONE", bg = "NONE", sp = c._orange, undercurl = true })
  hl(0, "SpellLocal", { fg = "NONE", bg = "NONE", sp = c._green, underline = true })
  hl(0, "SpellRare", { fg = "NONE", bg = "NONE", sp = c._red, underline = true })
  hl(0, "NormalNC", { fg = c.fg, bg = c.bg })
  hl(0, "Pmenu", { fg = c.fg, bg = c.alt_bg })
  hl(0, "PmenuSel", { fg = c.bg, bg = c.alt_fg })
  hl(0, "WildMenu", { fg = c.bg, bg = c.alt_fg })
  hl(0, "CursorLine", { fg = "NONE", bg = c.bg, italic = true, bold = true })
  hl(0, "CursorLineNr", { fg = c.alt_fg, bg = "NONE", bold = true })
  hl(0, "Folded", { fg = c._grey_dark, bg = c.cursorline })
  hl(0, "FoldColumn", { fg = c._grey_dark, bg = c.bg })
  hl(0, "LineNr", { fg = c._grey_dark, bg = "NONE" })
  hl(0, "FloatBorder", { fg = c._blue, bg = c.alt_bg })
  hl(0, "Whitespace", { fg = c.cursorline, bg = "NONE" })
  hl(0, "VertSplit", { fg = c._grey_dark, bg = c.bg })
  hl(0, "CursorColumn", { fg = "NONE", bg = c.cursorline })
  hl(0, "ColorColumn", { fg = "NONE", bg = c.cursorline })
  hl(0, "NormalFloat", { fg = c.fg, bg = c.alt_bg })
  hl(0, "Visual", { fg = "NONE", bg = c._light_blue })
  hl(0, "VisualNOS", { fg = "NONE", bg = c.cursorline })
  hl(0, "WarningMsg", { fg = c._red, bg = c.bg })
  hl(0, "DiffText", { fg = c.bg, bg = c._red })
  hl(0, "DiffAdd", { fg = c._green, bg = c.system_green_light })
  hl(0, "DiffChange", { fg = c._orange, bg = c.system_orange_light, underline = true })
  hl(0, "DiffDelete", { fg = c._red, bg = c.system_pink_light })
  hl(0, "QuickFixLine", { fg = "NONE", bg = c.cursorline })
  hl(0, "PmenuSbar", { fg = "NONE", bg = c.cursorline })
  hl(0, "PmenuThumb", { fg = "NONE", bg = c._grey_dark })
  hl(0, "MatchWord", { fg = "NONE", bg = "NONE", underline = true })
  hl(0, "MatchParen", { fg = c._red, bg = "NONE", underline = true, bold = true })
  hl(0, "MatchWordCur", { fg = "NONE", bg = "NONE", underline = true })
  hl(0, "MatchParenCur", { fg = "NONE", bg = "NONE", underline = true })
  hl(0, "Cursor", { fg = c.bg, bg = c.cursor_bg })
  hl(0, "lCursor", { fg = c.bg, bg = c.cursor_bg })
  hl(0, "CursorIM", { fg = c.bg, bg = c.cursor_bg })
  hl(0, "TermCursor", { fg = c.bg, bg = c.cursor_bg })
  hl(0, "TermCursorNC", { fg = c.bg, bg = c.cursor_bg })
  hl(0, "Conceal", { fg = c._grey_dark, bg = "NONE" })
  hl(0, "Directory", { fg = c._green, bg = "NONE" })
  hl(0, "SpecialKey", { fg = c.alt_fg, bg = "NONE", bold = true })
  hl(0, "ErrorMsg", { fg = c._red, bg = c.bg, bold = true })
  hl(0, "Search", { fg = c.fg, bg = c._yellow })
  hl(0, "IncSearch", { fg = c.bg, bg = c._orange })
  hl(0, "Substitute", { fg = c.bg, bg = c._orange })
  hl(0, "MoreMsg", { fg = c._orange, bg = "NONE" })
  hl(0, "Question", { fg = c._orange, bg = "NONE" })
  hl(0, "EndOfBuffer", { fg = c.bg, bg = "NONE" })
  hl(0, "NonText", { fg = c.cursorline, bg = "NONE" })
  hl(0, "TabLine", { fg = c._grey_dark, bg = c.line })
  hl(0, "TabLineSel", { fg = c.fg, bg = c.bg })
  hl(0, "TabLineFill", { fg = c.line, bg = c.line })

  -- Code
  hl(0, "Comment", { fg = c._grey_dark, bg = "NONE", italic = true })
  hl(0, "Variable", { fg = c.fg, bg = "NONE" })
  hl(0, "String", { fg = c._green, bg = "NONE" })
  hl(0, "Character", { fg = c._green, bg = "NONE" })
  hl(0, "Number", { fg = c._orange, bg = "NONE" })
  hl(0, "Float", { fg = c._orange, bg = "NONE" })
  hl(0, "Boolean", { fg = c._red, bg = "NONE" })
  hl(0, "Constant", { fg = c._red, bg = "NONE" })
  hl(0, "Type", { fg = c._pink, bg = "NONE" })
  hl(0, "Function", { fg = c._red, bg = "NONE" })
  hl(0, "Keyword", { fg = c.alt_fg, bg = "NONE" })
  hl(0, "Conditional", { fg = c._red, bg = "NONE" })
  hl(0, "Repeat", { fg = c._purple, bg = "NONE" })
  hl(0, "Operator", { fg = c.fg, bg = "NONE" })
  hl(0, "PreProc", { fg = c._pink, bg = "NONE" })
  hl(0, "Include", { fg = c._pink, bg = "NONE" })
  hl(0, "Exception", { fg = c._red, bg = "NONE" })
  hl(0, "StorageClass", { fg = c._pink, bg = "NONE" })
  hl(0, "Structure", { fg = c._pink, bg = "NONE" })
  hl(0, "Typedef", { fg = c._pink, bg = "NONE" })
  hl(0, "Define", { fg = c._pink, bg = "NONE" })
  hl(0, "Macro", { fg = c.alt_fg, bg = "NONE" })
  hl(0, "Debug", { fg = c._red, bg = "NONE" })
  hl(0, "Title", { fg = c.alt_fg, bg = "NONE", bold = true })
  hl(0, "Label", { fg = c.fg, bg = "NONE" })
  hl(0, "SpecialChar", { fg = c._green, bg = "NONE" })
  hl(0, "Delimiter", { fg = c.alt_fg, bg = "NONE" })
  hl(0, "SpecialComment", { fg = c._pink_alt, bg = "NONE", italic = true })
  hl(0, "Tag", { fg = c.alt_fg, bg = "NONE" })
  hl(0, "Bold", { fg = "NONE", bg = "NONE", bold = true })
  hl(0, "Italic", { fg = "NONE", bg = "NONE", italic = true })
  hl(0, "Underlined", { fg = "NONE", bg = "NONE", underline = true })
  hl(0, "Ignore", { fg = c._grey_dark, bg = "NONE" })
  hl(0, "Todo", { fg = c._red, bg = "NONE", bold = true })
  hl(0, "Error", { fg = c._red, bg = "NONE", bold = true })
  hl(0, "Statement", { fg = c._blue, bg = "NONE" })
  hl(0, "Identifier", { fg = c.fg, bg = "NONE" })
  hl(0, "PreCondit", { fg = c._pink, bg = "NONE" })
  hl(0, "Special", { fg = c._pink_alt, bg = "NONE" })

  hl(0, "TelescopeSelection", { fg = "NONE", bg = c._blue })
  hl(0, "TelescopeSelectionCaret", { fg = c._red, bg = c.system_blue })
  hl(0, "TelescopeMatching", { fg = c.cyan, bg = "NONE", bold = true, italic = true })
  hl(0, "TelescopeBorder", { fg = c._red, bg = "NONE" })
  hl(0, "TelescopeNormal", { fg = c.fg, bg = c.alt_bg })
  hl(0, "TelescopePromptTitle", { fg = c._white, bg = "NONE" })
  hl(0, "TelescopePromptPrefix", { fg = c._blue, bg = "NONE" })
  hl(0, "TelescopeResultsTitle", { fg = c._white, bg = "NONE" })
  hl(0, "TelescopePreviewTitle", { fg = c._red, bg = "NONE" })
  hl(0, "TelescopePromptCounter", { fg = c._red, bg = "NONE" })
  hl(0, "TelescopePreviewHyphen", { fg = c._red, bg = "NONE" })

  --Language

  hl(0, "xmlTag", { fg = c.cyan, bg = "NONE" })
  hl(0, "xmlTagName", { fg = c.cyan, bg = "NONE" })
  hl(0, "xmlEndTag", { fg = c.cyan, bg = "NONE" })
  hl(0, "yamlPlainScalar", { fg = c.orange, bg = "NONE" })
  hl(0, "yamlTSField", { fg = c.blue, bg = "NONE" })
  hl(0, "luaFunc", { fg = c.orange, bg = "NONE" })
  hl(0, "luaFunction", { fg = c.blue, bg = "NONE" })
  hl(0, "hclTSPunctSpecial", { fg = c.alt_fg, bg = "NONE" })
  hl(0, "htmlH1", { fg = c.fg, bg = "NONE" })
  hl(0, "htmlH2", { fg = c.fg, bg = "NONE" })
  hl(0, "htmlH3", { fg = c.fg, bg = "NONE" })
  hl(0, "htmlH4", { fg = c.fg, bg = "NONE" })
  hl(0, "htmlH5", { fg = c.fg, bg = "NONE" })
  hl(0, "htmlH6", { fg = c.fg, bg = "NONE" })
  hl(0, "htmlHead", { fg = c.fg, bg = "NONE" })
  hl(0, "htmlTitle", { fg = c.fg, bg = "NONE" })
  hl(0, "htmlArg", { fg = c.fg, bg = "NONE" })
  hl(0, "htmlTag", { fg = c.blue, bg = "NONE" })
  hl(0, "htmlTagN", { fg = c.blue, bg = "NONE" })
  hl(0, "htmlTagName", { fg = c.blue, bg = "NONE" })
  hl(0, "htmlComment", { fg = c.green, bg = "NONE" })
  hl(0, "htmlLink", { fg = c.orange, bg = "NONE", underline = true })
  hl(0, "cssBraces", { fg = c.fg, bg = "NONE" })
  hl(0, "cssInclude", { fg = c.purple, bg = "NONE" })
  hl(0, "cssTagName", { fg = c.orange, bg = "NONE" })
  hl(0, "cssClassName", { fg = c.orange, bg = "NONE" })
  hl(0, "cssPseudoClass", { fg = c.orange, bg = "NONE" })
  hl(0, "cssPseudoClassId", { fg = c.orange, bg = "NONE" })
  hl(0, "cssPseudoClassLang", { fg = c.orange, bg = "NONE" })
  hl(0, "cssIdentifier", { fg = c.orange, bg = "NONE" })
  hl(0, "cssProp", { fg = c.fg, bg = "NONE" })
  hl(0, "cssDefinition", { fg = c.fg, bg = "NONE" })
  hl(0, "cssAttr", { fg = c.orange, bg = "NONE" })
  hl(0, "cssAttrRegion", { fg = c.orange, bg = "NONE" })
  hl(0, "cssColor", { fg = c.orange, bg = "NONE" })
  hl(0, "cssFunction", { fg = c.purple, bg = "NONE" })
  hl(0, "cssFunctionName", { fg = c.orange, bg = "NONE" })
  hl(0, "cssVendor", { fg = c.orange, bg = "NONE" })
  hl(0, "cssValueNumber", { fg = c.orange, bg = "NONE" })
  hl(0, "cssValueLength", { fg = c.orange, bg = "NONE" })
  hl(0, "cssUnitDecorators", { fg = c.orange, bg = "NONE" })
  hl(0, "cssStyle", { fg = c.fg, bg = "NONE" })
  hl(0, "cssImportant", { fg = c.blue, bg = "NONE" })
  hl(0, "jsonKeyword", { fg = c.blue, bg = "NONE" })
  hl(0, "yamlBlockMappingKey", { fg = c.blue, bg = "NONE" })
  hl(0, "tomlTSProperty", { fg = c.blue, bg = "NONE" })
  hl(0, "@variable.lua", { fg = c._light_blue, bg = "NONE" })

  -- markdown
  hl(0, "markdownBlockquote", { fg = c.orange, bg = "NONE" })
  hl(0, "markdownCode", { fg = c.orange, bg = "NONE" })
  hl(0, "markdownCodeBlock", { fg = c.orange, bg = "NONE" })
  hl(0, "markdownCodeDelimiter", { fg = c.orange, bg = "NONE" })
  hl(0, "markdownH1", { link = "Title" })
  hl(0, "markdownH2", { link = "Title" })
  hl(0, "markdownH3", { link = "Title" })
  hl(0, "markdownH4", { link = "Title" })
  hl(0, "markdownH5", { link = "Title" })
  hl(0, "markdownH6", { link = "Title" })
  hl(0, "markdownHeadingDelimiter", { fg = c.blue, bg = "NONE" })
  hl(0, "markdownHeadingRule", { fg = c.fg, bg = "NONE", bold = true })
  hl(0, "markdownId", { link = "Identifier" })
  hl(0, "markdownIdDeclaration", { fg = c.blue, bg = "NONE" })
  hl(0, "markdownIdDelimiter", { fg = c.light_gray, bg = "NONE" })
  hl(0, "markdownLinkDelimiter", { fg = c.light_gray, bg = "NONE" })
  hl(0, "markdownBold", { fg = c.blue, bg = "NONE", bold = true })
  hl(0, "markdownItalic", { link = "Italic" })
  hl(0, "markdownBoldItalic", { fg = c.orange, bg = "NONE", bold = true, italic = true })
  hl(0, "markdownListMarker", { fg = c.blue, bg = "NONE" })
  hl(0, "markdownOrderedListMarker", { fg = c.purple, bg = "NONE" })
  hl(0, "markdownRule", { fg = c.gray, bg = "NONE" })
  hl(0, "markdownUrl", { fg = c.cyan, bg = "NONE", underdotted = true })
  hl(0, "markdownLinkText", { fg = c.blue, bg = "NONE" })
  hl(0, "markdownFootnote", { fg = c.orange, bg = "NONE" })
  hl(0, "markdownFootnoteDefinition", { fg = c.orange, bg = "NONE" })
  hl(0, "markdownEscape", { fg = c.orange, bg = "NONE" })
end

function theme.setup()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
  end

  vim.g.colors_name = "hqos_dark"
  theme.set_highlights()
end

return theme
