local white_shade = {
  alabaster = "#EDEAE0",
  alice_blue = "#F0F8FF",
  almond = "#EFDECD",
  anti_flash_white = "#F2F3F4",
  antique_white = "#FAEBD7",
  azure_white = "#F0FFFF",
  baby_powder = "#FEFEFA",
  beige = "#F5F5DC",
  bone = "#E3DAC9",
  champagne = "#F7E7CE",

  cornsilk = "#FFF8DC",
  cool_mint = "#DDEBEC",
  cosmic_latte = "#FFF8E7",
  cream = "#FFFDD0",
  cultured_pearl = "#F5F5F5",
  dutch_white = "#EFDFBB",
  eggshell = "#F0EAD6",
  extra_light_almond = "#EEE6CF",
  flax = "#EEDC82",
  floral_white = "#FFFAF0",

  ghost_white = "#F8F8FF",
  honeydew = "#F0FFF0",
  isabelline = "#F4F0EC",
  ivory = "#FFFFF0",
  lavender_blush = "#FFF0F5",
  lemon_chiffon = "#FFFACD",
  linen = "#FAF0E6",
  magnolia = "#F3ECE4",
  mint_cream = "#F5FFFA",
  misty_rost = "#FFE4E1",

  navajo_white = "#FFDEAD",
  nyanza = "#E9FFDB",
  old_lace = "#FDF5E6",
  papaya_white = "#FFEFD5",
  parchment = "#F1E9D2",
  peach = "#FFE5B4",
  pearl = "#EAE0C8",
  platinum = "#E5E4E2",
  seasalt = "#F7F7F7",
  seashell = "#FFF5EE",

  snow = "#FFFAFA",
  snow_drift = "#F3F3F3",
  vanilla = "#F3E5AB",
  very_light_rose = "#F7E1E3",
  white = "#FFFFFF",
  white_smoke = "#F5F5F5",
}
return white_shade
